package com.example.multitrans

data class LanguageModel(
    val code: String,
    val name: String,
    val flag: String,
    var isSelected: Boolean = false
)

object LanguageData {
    val allLanguages = listOf(
        LanguageModel("en", "English", "🇺🇸"),
        LanguageModel("af", "Afrikaans", "🇿🇦"),
        LanguageModel("sq", "Albanian", "🇦🇱"),
        LanguageModel("ar", "Arabic", "🇸🇦"),
        LanguageModel("be", "Belarusian", "🇧🇾"),
        LanguageModel("bn", "Bengali", "🇧🇩"),
        LanguageModel("bg", "Bulgarian", "🇧🇬"),
        LanguageModel("ca", "Catalan", "🇪🇸"),
        LanguageModel("zh", "Chinese", "🇨🇳"),
        LanguageModel("hr", "Croatian", "🇭🇷"),
        LanguageModel("cs", "Czech", "🇨🇿"),
        LanguageModel("da", "Danish", "🇩🇰"),
        LanguageModel("nl", "Dutch", "🇳🇱"),
        LanguageModel("eo", "Esperanto", "🌍"),
        LanguageModel("et", "Estonian", "🇪🇪"),
        LanguageModel("fi", "Finnish", "🇫🇮"),
        LanguageModel("fr", "French", "🇫🇷"),
        LanguageModel("gl", "Galician", "🇪🇸"),
        LanguageModel("ka", "Georgian", "🇬🇪"),
        LanguageModel("de", "German", "🇩🇪"),
        LanguageModel("el", "Greek", "🇬🇷"),
        LanguageModel("gu", "Gujarati", "🇮🇳"),
        LanguageModel("ht", "Haitian Creole", "🇭🇹"),
        LanguageModel("he", "Hebrew", "🇮🇱"),
        LanguageModel("hi", "Hindi", "🇮🇳"),
        LanguageModel("hu", "Hungarian", "🇭🇺"),
        LanguageModel("is", "Icelandic", "🇮🇸"),
        LanguageModel("id", "Indonesian", "🇮🇩"),
        LanguageModel("ga", "Irish", "🇮🇪"),
        LanguageModel("it", "Italian", "🇮🇹"),
        LanguageModel("ja", "Japanese", "🇯🇵"),
        LanguageModel("kn", "Kannada", "🇮🇳"),
        LanguageModel("ko", "Korean", "🇰🇷"),
        LanguageModel("lv", "Latvian", "🇱🇻"),
        LanguageModel("lt", "Lithuanian", "🇱🇹"),
        LanguageModel("mk", "Macedonian", "🇲🇰"),
        LanguageModel("ms", "Malay", "🇲🇾"),
        LanguageModel("mt", "Maltese", "🇲🇹"),
        LanguageModel("mr", "Marathi", "🇮🇳"),
        LanguageModel("no", "Norwegian", "🇳🇴"),
        LanguageModel("fa", "Persian", "🇮🇷"),
        LanguageModel("pl", "Polish", "🇵🇱"),
        LanguageModel("pt", "Portuguese", "🇵🇹"),
        LanguageModel("ro", "Romanian", "🇷🇴"),
        LanguageModel("ru", "Russian", "🇷🇺"),
        LanguageModel("sk", "Slovak", "🇸🇰"),
        LanguageModel("sl", "Slovenian", "🇸🇮"),
        LanguageModel("es", "Spanish", "🇪🇸"),
        LanguageModel("sw", "Swahili", "🇰🇪"),
        LanguageModel("sv", "Swedish", "🇸🇪"),
        LanguageModel("tl", "Tagalog", "🇵🇭"),
        LanguageModel("ta", "Tamil", "🇮🇳"),
        LanguageModel("te", "Telugu", "🇮🇳"),
        LanguageModel("th", "Thai", "🇹🇭"),
        LanguageModel("tr", "Turkish", "🇹🇷"),
        LanguageModel("uk", "Ukrainian", "🇺🇦"),
        LanguageModel("ur", "Urdu", "🇵🇰"),
        LanguageModel("vi", "Vietnamese", "🇻🇳"),
        LanguageModel("cy", "Welsh", "🏴󠁧󠁢󠁷󠁬󠁳󠁿")
    )
}
